Transfer messages Schemas and Shapes validation
International-Data-Spaces-Association/ids-specification pull request #173
Opened 2023-11-07 13:59 UTC by simantvermasap

2023-11-08 12:37 UTC, ssteinbuss commented on catalog/message/schema/catalog-schema.json
> +                "foaf:primaryTopiy"
Shouldn' t this be "foaf:primaryTopic" ?

2023-11-14 17:32 UTC, sebbader-sap requested changes

2023-11-14 17:33 UTC, sebbader-sap commented
Seems like I didn't submit my review...

2023-11-30 08:06 UTC, sebbader-sap commented
Updates of this PR are already incorporated in another activity and will be presented from there.

2023-11-30 08:06 UTC, closed without merging