Replace providerId/consumerId with odrl:assigner / odrl:assignee
International-Data-Spaces-Association/ids-specification pull request #213
Opened 2024-02-06 16:29 UTC by sebbader-sap

Solves #195

2024-02-07 16:09 UTC, juliapampus requested changes
"Solves" is not a [closing keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) for GitHub. Please use one of them, this automates closing issues when a PR is merged.

You only checked for `dspace:providerId` and `dspace:consumerId`. Please also search for `providerId` and `consumerId`. For instance, the protocol document (line 102) contains some leftovers.

2024-02-07 16:09 UTC, juliapampus commented on negotiation/contract.negotiation.binding.https.md
This ToC is a real nighmare (especially rendered). Can you please remove the level 3+ headers for sec 2 and 3 from it (i.e. GET/POST, request, response)

2024-02-07 19:49 UTC, mkollenstart approved these changes
Since it is not really part of this pull request, I'm still approving, but I think we should set a bit more representative identifiers in the examples. Especially in the case of URNs.

2024-02-08 10:01 UTC, sebbader-sap commented on negotiation/contract.negotiation.binding.https.md
done

2024-02-08 10:03 UTC, sebbader-sap commented
> You only checked for `dspace:providerId` and `dspace:consumerId`. Please also search for `providerId` and `consumerId`. For instance, the protocol document (line 102) contains some leftovers.

@juliapampus I have pushed the changes, please have a quick look.

2024-02-15 07:20 UTC, ssteinbuss approved these changes

2024-02-15 08:18 UTC, juliapampus approved these changes

2024-02-15 08:18 UTC, merged