Add participant id to catalog
International-Data-Spaces-Association/ids-specification pull request #226
Opened 2024-02-13 12:17 UTC by jimmarino

Adds "dspace:participantId" to the DCAT Catalog response.

Closes #196

2024-02-13 12:23 UTC, sebbader-sap requested changes
There are also adjustments needed in https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/message/schema/catalog-schema.json and https://github.com/International-Data-Spaces-Association/ids-specification/blob/main/catalog/message/shape/dcat-shapes.ttl. If you make it a branch of this repo, I can push the fixes directly.

2024-02-15 08:30 UTC, juliapampus requested changes

2024-02-15 08:30 UTC, juliapampus commented on catalog/catalog.protocol.md
> +The identifier of the participant providing the `Catalog` is specified using the `dspace:participantId` attribute on that `DCAT Catalog`.
```suggestion
The identifier of the participant providing the [Catalog](../model/terminology.md#catalog) is specified using the `dspace:participantId` attribute on that [DCAT Catalog](https://www.w3.org/TR/vocab-dcat-3/#Class:Catalog).
```
Consistent usage of links.

2024-02-15 08:30 UTC, juliapampus commented on catalog/message/example/catalog.json
As this JSON is changed.. shouldn't this also result in changes to the schemas and shapes?

2024-02-15 09:17 UTC, jimmarino commented on catalog/message/example/catalog.json
Yes @sebbader-sap will be fixing those

2024-02-15 09:31 UTC, sebbader-sap approved these changes

2024-02-16 08:12 UTC, juliapampus approved these changes

2024-02-16 08:39 UTC, merged