Adds auth description to common bindings document
International-Data-Spaces-Association/ids-specification pull request #227
Opened 2024-02-13 12:27 UTC by jimmarino

Adds a note about authorization to the common bindings document.

Closes #203

2024-02-14 16:38 UTC, sebbader-sap approved these changes

2024-02-15 06:55 UTC, ssteinbuss approved these changes

2024-02-15 08:24 UTC, juliapampus requested changes
The authorization section should also be removed from the transfer and negotiation http binding documents (Section 1.3).

2024-02-15 08:33 UTC, juliapampus commented
Same goes for the catalog https binding @jimmarino sry, I thought this was already changed. Also sec 1.3.

2024-02-15 08:37 UTC, jimmarino commented
> Same goes for the catalog https binding @jimmarino sry, I thought this was already changed. Also sec 1.3.

@juliapampus done

2024-02-15 08:58 UTC, juliapampus approved these changes

2024-02-15 09:12 UTC, merged