Removing inital figure
International-Data-Spaces-Association/ids-specification pull request #245
Opened 2024-02-23 08:37 UTC by ssteinbuss

Removing figure

* old and new figures were included
* Now only the current figre is included

2024-02-23 12:59 UTC, sebbader-sap approved these changes

2024-02-23 13:00 UTC, sebbader-sap commented
@ssteinbuss I think @juliapampus added both diagrams on purpose. I therefore re-added the "initial" one, plus diagram titles explaining the difference. 
@juliapampus can you confirm?

2024-02-23 13:06 UTC, juliapampus requested changes
What is the purpose of this PR? The two figures were created on purpose.

2024-02-23 14:33 UTC, ssteinbuss commented
This was not really clear by reading, so I am in favour of Sebastians captions

2024-02-23 15:02 UTC, juliapampus requested changes

2024-02-27 09:22 UTC, jimmarino approved these changes

2024-02-27 09:26 UTC, merged